source 'https://rubygems.org'
#git_source(:github) { |repo| 'https://github.com/#{repo}.git' }

ruby '2.5.1'

gem 'bootsnap', '>= 1.1.0', require: false
#gem 'common_models', github: 'common-group/common_models', branch: 'develop'
gem 'common_models', path: './vendor/gems/common_models'
gem 'concurrent-ruby', '1.1.5', require: 'concurrent'
gem 'excelinator'
gem 'jwt'
gem 'loofah', '>= 2.2.3'
gem 'mutations'
gem 'pagarme', '2.4.0'
gem 'postgres-copy'
gem 'puma', '~> 3.11'
gem 'pundit', '2.0.0.beta1'
gem 'rack', '>= 2.0.6'
gem 'rack-cors'
gem 'rails', '~> 5.2.2.1'
# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'database_cleaner'
  gem 'factory_bot', '4.11.1'
  gem 'pry'
  gem 'rails-controller-testing'
  gem 'rspec'
  gem 'rspec_api_documentation'
  gem 'rspec-rails'
  gem 'shoulda-matchers', '4.0.0.rc1'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
